## Travel Mode Dataset (NTS0409)

In this section, the National Travel Survey (NTS0409) dataset is used to construct the travel mode behaviour component of the framework.

The NTS0409 dataset provides the average number of trips per person per year, disaggregated by trip purpose and travel mode. Specifically, it records how frequently different travel modes (e.g., walking, car driver, bus) are used for each trip purpose (e.g., commuting, shopping, leisure).

### Purpose of Using This Dataset

The objective of using this dataset is to derive the conditional probability distribution of travel modes given a trip purpose:

P (Travel Mode | Trip Purpose)

Within the proposed framework, the trip purpose is first determined based on demographic-specific mobility patterns. Given this trip purpose, the NTS0409 dataset is then used to estimate how individuals choose their travel mode.

### Data Processing Overview

Since the dataset reports annual trip frequencies rather than probabilities, a normalisation step is required. For each trip purpose, the number of trips across all travel modes is summed, and each mode-specific value is divided by this total. This converts the raw trip counts into a probability distribution over travel modes.

As a result, the final output of this step is a travel mode probability matrix, where each row corresponds to a trip purpose and each row sums to 1.

### Step 1: Import dataset

In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [2]:
nts0409a = pd.read_excel('../dataset(mobility)/nts0409-Average number of trips and distance travelled by purpose and main mode England, 2002 onwards.ods', sheet_name='NTS0409a_trips', skiprows=5)

In [3]:
display(nts0409a.head())

,Year,Main mode,Commuting,Business,Education or escort education,Shopping,Other escort,Personal business,Leisure [note 2],Just walk [note 8],Other [note 8],All purposes,Unweighted sample size: trips (thousands)
0,2002,"Walk [notes 3, 4]",16.349172,2.865760,44.115380,59.249569,13.319239,34.740433,52.424669,40.874737,0.073657,264.012617,66.356
1,2002,Pedal cycle [note 5],6.547287,0.612595,1.833587,2.363763,0.364849,1.308123,4.999214,0.000000,0.000000,18.029417,4.542
2,2002,Car or van driver,95.832523,26.226708,23.895374,90.122423,57.491243,47.131800,97.393661,0.000000,0.320400,438.414132,116.736
3,2002,Car or van passenger,16.985655,2.400159,25.759621,46.019618,30.738702,24.580872,93.407171,0.000000,0.043487,239.935284,63.814
4,2002,Motorcycle,2.005321,0.041155,0.051922,0.471992,0.114125,0.297173,0.864034,0.000000,0.006289,3.852011,0.977

In [4]:
nts0409a.columns

Index(['Year', 'Main mode', 'Commuting', 'Business',
       'Education or escort education', 'Shopping', 'Other escort',
       'Personal business', 'Leisure [note 2]', 'Just walk [note 8]',
       'Other [note 8]', 'All purposes',
       'Unweighted sample size: trips (thousands)'],
      dtype='object')

In [5]:
nts0409a['Year'].unique()

array([2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023,
       2024])

In [6]:
nts0409a_processed = nts0409a.copy()
nts0409a_processed = nts0409a_processed[
    nts0409a_processed['Year'] == 2024].copy()

In [7]:
nts0409a_processed

,Year,Main mode,Commuting,Business,Education or escort education,Shopping,Other escort,Personal business,Leisure [note 2],Just walk [note 8],Other [note 8],All purposes,Unweighted sample size: trips (thousands)
308,2024,"Walk [notes 3, 4]",14.090618,2.126124,48.251124,46.972684,8.898228,20.848153,41.463671,84.617743,0.000000,267.268345,82.474
309,2024,Pedal cycle [note 5],4.657803,0.453976,1.397357,1.477198,0.161975,0.799048,6.259976,0.000000,0.000000,15.207333,4.377
310,2024,Car or van driver,60.443130,16.798872,27.906054,76.310214,43.284308,35.432481,96.676435,0.000000,0.501423,357.352918,114.342
311,2024,Car or van passenger,8.244171,1.420307,27.620174,29.601703,21.687584,18.562586,82.233065,0.000000,0.067612,189.437203,57.253
312,2024,Motorcycle,1.037418,0.044498,0.021068,0.207584,0.015937,0.066523,0.597993,0.000000,0.000000,1.991021,0.593
313,2024,Other private transport [note 6],0.512051,0.182144,3.066882,0.782541,0.584211,0.676074,2.255293,0.000000,0.000000,8.059197,2.481
314,2024,Bus in London,2.843678,0.346400,2.445149,2.528714,0.381459,1.364079,3.196108,0.000000,0.009989,13.115577,4.064
315,2024,Other local bus,5.961216,0.562696,5.565624,6.072279,0.999481,2.617272,6.274703,0.000000,0.015282,28.068554,7.749
316,2024,Non-local bus,0.042597,0.000000,0.000000,0.004632,0.000000,0.016646,0.342390,0.000000,0.000000,0.406265,0.120
317,2024,London Underground,4.063161,0.530284,0.697621,0.510131,0.067982,0.559338,3.113857,0.000000,0.000000,9.542374,2.597
318,2024,Surface Rail,7.716544,1.674590,1.382703,1.264324,0.246320,0.962511,7.446402,0.000000,0.000000,20.693394,5.829
319,2024,Taxi or minicab,1.167798,0.289642,0.736568,0.847274,0.341768,1.227330,4.195103,0.000000,0.000000,8.805484,2.383
320,2024,Other public transport [note 7],0.505975,0.052184,0.150551,0.274174,0.069777,0.149237,0.656897,0.000000,0.000000,1.858794,0.504
321,2024,All modes,111.286158,24.481718,119.240875,166.853454,76.739029,83.281280,254.711895,84.617743,0.594307,921.806459,284.766

In [8]:
# melt means to transform the data from wide format to long format. 
# In this case, we are transforming the data so that each row represents a single trip purpose and its corresponding number of trips for each main mode of transport in the year 2024.
nts0409a_long = nts0409a_processed.melt(
    id_vars=['Year', 'Main mode'],
    value_vars=[col for col in nts0409a_processed.columns if col not in ['Year', 'Main mode']],
    var_name="Purpose",
    value_name="Trips"
)

In [9]:
print(nts0409a_long.head())

   Year             Main mode    Purpose      Trips
0  2024     Walk [notes 3, 4]  Commuting  14.090618
1  2024  Pedal cycle [note 5]  Commuting   4.657803
2  2024     Car or van driver  Commuting  60.443130
3  2024  Car or van passenger  Commuting   8.244171
4  2024            Motorcycle  Commuting   1.037418

In [10]:
nts0409a_long = nts0409a_long[
    ~nts0409a_long['Purpose'].isin([
        'All purposes',
        'Unweighted sample size: trips (thousands)'
    ])
]

nts0409a_long = nts0409a_long[
    nts0409a_long['Main mode'] != 'All modes'
]

nts0409a_long['Probability'] = (
    nts0409a_long['Trips'] /
    nts0409a_long.groupby('Purpose')['Trips'].transform('sum')
)

In [11]:
nts0409a_long

,Year,Main mode,Purpose,Trips,Probability
0,2024,"Walk [notes 3, 4]",Commuting,14.090618,0.126616
1,2024,Pedal cycle [note 5],Commuting,4.657803,0.041854
2,2024,Car or van driver,Commuting,60.443130,0.543133
3,2024,Car or van passenger,Commuting,8.244171,0.074081
4,2024,Motorcycle,Commuting,1.037418,0.009322
5,2024,Other private transport [note 6],Commuting,0.512051,0.004601
6,2024,Bus in London,Commuting,2.843678,0.025553
7,2024,Other local bus,Commuting,5.961216,0.053567
8,2024,Non-local bus,Commuting,0.042597,0.000383
9,2024,London Underground,Commuting,4.063161,0.036511
10,2024,Surface Rail,Commuting,7.716544,0.069340
11,2024,Taxi or minicab,Commuting,1.167798,0.010494
12,2024,Other public transport [note 7],Commuting,0.505975,0.004547
14,2024,"Walk [notes 3, 4]",Business,2.126124,0.086845
15,2024,Pedal cycle [note 5],Business,0.453976,0.018543
16,2024,Car or van driver,Business,16.798872,0.686180
17,2024,Car or van passenger,Business,1.420307,0.058015
18,2024,Motorcycle,Business,0.044498,0.001818
19,2024,Other private transport [note 6],Business,0.182144,0.007440
20,2024,Bus in London,Business,0.346400,0.014149
21,2024,Other local bus,Business,0.562696,0.022984
22,2024,Non-local bus,Business,0.000000,0.000000
23,2024,London Underground,Business,0.530284,0.021660
24,2024,Surface Rail,Business,1.674590,0.068402
25,2024,Taxi or minicab,Business,0.289642,0.011831
26,2024,Other public transport [note 7],Business,0.052184,0.002132
28,2024,"Walk [notes 3, 4]",Education or escort education,48.251124,0.404653
29,2024,Pedal cycle [note 5],Education or escort education,1.397357,0.011719
30,2024,Car or van driver,Education or escort education,27.906054,0.234031
31,2024,Car or van passenger,Education or escort education,27.620174,0.231633
32,2024,Motorcycle,Education or escort education,0.021068,0.000177
33,2024,Other private transport [note 6],Education or escort education,3.066882,0.025720
34,2024,Bus in London,Education or escort education,2.445149,0.020506
35,2024,Other local bus,Education or escort education,5.565624,0.046675
36,2024,Non-local bus,Education or escort education,0.000000,0.000000
37,2024,London Underground,Education or escort education,0.697621,0.005851
38,2024,Surface Rail,Education or escort education,1.382703,0.011596
39,2024,Taxi or minicab,Education or escort education,0.736568,0.006177
40,2024,Other public transport [note 7],Education or escort education,0.150551,0.001263
42,2024,"Walk [notes 3, 4]",Shopping,46.972684,0.281521
43,2024,Pedal cycle [note 5],Shopping,1.477198,0.008853
44,2024,Car or van driver,Shopping,76.310214,0.457349
45,2024,Car or van passenger,Shopping,29.601703,0.177411
46,2024,Motorcycle,Shopping,0.207584,0.001244
47,2024,Other private transport [note 6],Shopping,0.782541,0.004690
48,2024,Bus in London,Shopping,2.528714,0.015155
49,2024,Other local bus,Shopping,6.072279,0.036393
50,2024,Non-local bus,Shopping,0.004632,0.000028
51,2024,London Underground,Shopping,0.510131,0.003057
52,2024,Surface Rail,Shopping,1.264324,0.007577
53,2024,Taxi or minicab,Shopping,0.847274,0.005078
54,2024,Other public transport [note 7],Shopping,0.274174,0.001643
56,2024,"Walk [notes 3, 4]",Other escort,8.898228,0.115954
57,2024,Pedal cycle [note 5],Other escort,0.161975,0.002111
58,2024,Car or van driver,Other escort,43.284308,0.564046
59,2024,Car or van passenger,Other escort,21.687584,0.282615
60,2024,Motorcycle,Other escort,0.015937,0.000208
61,2024,Other private transport [note 6],Other escort,0.584211,0.007613
62,2024,Bus in London,Other escort,0.381459,0.004971
63,2024,Other local bus,Other escort,0.999481,0.013024
64,2024,Non-local bus,Other escort,0.000000,0.000000
65,2024,London Underground,Other escort,0.067982,0.000886
66,2024,Surface Rail,Other escort,0.246320,0.003210
67,2024,Taxi or minicab,Other escort,0.341768,0.004454
68,2024,Other public transport [note 7],Other escort,0.069777,0.000909
70,2024,"Walk [notes 3, 4]",Personal business,20.848153,0.250334
71,2024,Pedal cycle [note 5],Personal business,0.799048,0.009595
72,2024,Car or van driver,Personal business,35.432481,0.425456
73,2024,Car or van passenger,Personal business,18.562586,0.222890
74,2024,Motorcycle,Personal business,0.066523,0.000799
75,2024,Other private transport [note 6],Personal business,0.676074,0.008118
76,2024,Bus in London,Personal business,1.364079,0.016379
77,2024,Other local bus,Personal business,2.617272,0.031427
78,2024,Non-local bus,Personal business,0.016646,0.000200
79,2024,London Underground,Personal business,0.559338,0.006716
80,2024,Surface Rail,Personal business,0.962511,0.011557
81,2024,Taxi or minicab,Personal business,1.227330,0.014737
82,2024,Other public transport [note 7],Personal business,0.149237,0.001792
84,2024,"Walk [notes 3, 4]",Leisure [note 2],41.463671,0.162787
85,2024,Pedal cycle [note 5],Leisure [note 2],6.259976,0.024577
86,2024,Car or van driver,Leisure [note 2],96.676435,0.379552
87,2024,Car or van passenger,Leisure [note 2],82.233065,0.322847
88,2024,Motorcycle,Leisure [note 2],0.597993,0.002348
89,2024,Other private transport [note 6],Leisure [note 2],2.255293,0.008854
90,2024,Bus in London,Leisure [note 2],3.196108,0.012548
91,2024,Other local bus,Leisure [note 2],6.274703,0.024635
92,2024,Non-local bus,Leisure [note 2],0.342390,0.001344
93,2024,London Underground,Leisure [note 2],3.113857,0.012225
94,2024,Surface Rail,Leisure [note 2],7.446402,0.029235
95,2024,Taxi or minicab,Leisure [note 2],4.195103,0.016470
96,2024,Other public transport [note 7],Leisure [note 2],0.656897,0.002579
98,2024,"Walk [notes 3, 4]",Just walk [note 8],84.617743,1.000000
99,2024,Pedal cycle [note 5],Just walk [note 8],0.000000,0.000000
100,2024,Car or van driver,Just walk [note 8],0.000000,0.000000
101,2024,Car or van passenger,Just walk [note 8],0.000000,0.000000
102,2024,Motorcycle,Just walk [note 8],0.000000,0.000000
103,2024,Other private transport [note 6],Just walk [note 8],0.000000,0.000000
104,2024,Bus in London,Just walk [note 8],0.000000,0.000000
105,2024,Other local bus,Just walk [note 8],0.000000,0.000000
106,2024,Non-local bus,Just walk [note 8],0.000000,0.000000
107,2024,London Underground,Just walk [note 8],0.000000,0.000000
108,2024,Surface Rail,Just walk [note 8],0.000000,0.000000
109,2024,Taxi or minicab,Just walk [note 8],0.000000,0.000000
110,2024,Other public transport [note 7],Just walk [note 8],0.000000,0.000000
112,2024,"Walk [notes 3, 4]",Other [note 8],0.000000,0.000000
113,2024,Pedal cycle [note 5],Other [note 8],0.000000,0.000000
114,2024,Car or van driver,Other [note 8],0.501423,0.843711
115,2024,Car or van passenger,Other [note 8],0.067612,0.113766
116,2024,Motorcycle,Other [note 8],0.000000,0.000000
117,2024,Other private transport [note 6],Other [note 8],0.000000,0.000000
118,2024,Bus in London,Other [note 8],0.009989,0.016808
119,2024,Other local bus,Other [note 8],0.015282,0.025715
120,2024,Non-local bus,Other [note 8],0.000000,0.000000
121,2024,London Underground,Other [note 8],0.000000,0.000000
122,2024,Surface Rail,Other [note 8],0.000000,0.000000
123,2024,Taxi or minicab,Other [note 8],0.000000,0.000000
124,2024,Other public transport [note 7],Other [note 8],0.000000,0.000000

In [12]:
#verify the sum of probabilities for each purpose equals 1
for purpose in nts0409a_long['Purpose'].unique():
    total_probability = nts0409a_long[nts0409a_long['Purpose'] == purpose]['Probability'].sum()
    print(f"Total probability for {purpose}: {total_probability}")

Total probability for Commuting: 0.9999999999999999
Total probability for Business: 1.0000000000000002
Total probability for Education or escort education: 1.0
Total probability for Shopping: 1.0
Total probability for Other escort: 1.0000000000000002
Total probability for Personal business: 0.9999999999999999
Total probability for Leisure [note 2]: 1.0
Total probability for Just walk [note 8]: 1.0
Total probability for Other [note 8]: 0.9999999999999999

In [13]:
nts0409a_matrix = nts0409a_long.pivot(
    index = 'Purpose',
    columns = 'Main mode',
    values = 'Probability'
)

In [14]:
nts0409a_matrix

Main mode,Bus in London,Car or van driver,Car or van passenger,London Underground,Motorcycle,Non-local bus,Other local bus,Other private transport [note 6],Other public transport [note 7],Pedal cycle [note 5],Surface Rail,Taxi or minicab,"Walk [notes 3, 4]"
Purpose,,,,,,,,,,,,,
Business,0.014149,0.686180,0.058015,0.021660,0.001818,0.000000,0.022984,0.007440,0.002132,0.018543,0.068402,0.011831,0.086845
Commuting,0.025553,0.543133,0.074081,0.036511,0.009322,0.000383,0.053567,0.004601,0.004547,0.041854,0.069340,0.010494,0.126616
Education or escort education,0.020506,0.234031,0.231633,0.005851,0.000177,0.000000,0.046675,0.025720,0.001263,0.011719,0.011596,0.006177,0.404653
Just walk [note 8],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
Leisure [note 2],0.012548,0.379552,0.322847,0.012225,0.002348,0.001344,0.024635,0.008854,0.002579,0.024577,0.029235,0.016470,0.162787
Other [note 8],0.016808,0.843711,0.113766,0.000000,0.000000,0.000000,0.025715,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Other escort,0.004971,0.564046,0.282615,0.000886,0.000208,0.000000,0.013024,0.007613,0.000909,0.002111,0.003210,0.004454,0.115954
Personal business,0.016379,0.425456,0.222890,0.006716,0.000799,0.000200,0.031427,0.008118,0.001792,0.009595,0.011557,0.014737,0.250334
Shopping,0.015155,0.457349,0.177411,0.003057,0.001244,0.000028,0.036393,0.004690,0.001643,0.008853,0.007577,0.005078,0.281521

In [15]:
for purpose in nts0409a_matrix.index:
    total_probability = nts0409a_matrix.loc[purpose].sum()
    print(f"Total probability for {purpose}: {total_probability}")

Total probability for Business: 1.0
Total probability for Commuting: 0.9999999999999999
Total probability for Education or escort education: 1.0
Total probability for Just walk [note 8]: 1.0
Total probability for Leisure [note 2]: 1.0
Total probability for Other [note 8]: 0.9999999999999999
Total probability for Other escort: 1.0000000000000002
Total probability for Personal business: 1.0000000000000002
Total probability for Shopping: 1.0